name: aws-deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on:
      - ubuntu-latest
    steps:
      - name: Check source
        uses: actions/checkout@v3
      - name: Setup JAVA
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Projects
        run: mvn clean install -DskipTests
      - name: Login To Dockerhub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t fitandtrack/fitandtrackapp .
      - name: Publish Image To Dockerhub
        run: docker push fitandtrack/fitandtrackapp:latest

  deploy:
    needs: build
    runs-on:
      - aws-ec2
    steps:
      - name: Pull The Image From Dockerhub
        run: docker pull fitandtrack/fitandtrackapp:latest
      - name: Delete Old Containers
        run: docker rm -f fit-and-track-app-container
      - name: Run Docker Container
        run: docker run -d -p 8080:8080 --name fit-and-track-app-container fitandtrack/fitandtrackapp
